const imgUrl = [
  "https://m.media-amazon.com/images/I/71zdEncDbPS._AC_UL320_.jpg",
  "https://m.media-amazon.com/images/I/61o0EbhjKDL._AC_UY218_.jpg",
  "https://m.media-amazon.com/images/I/518kSLmk08L._AC_UY218_.jpg",
  "https://m.media-amazon.com/images/I/61o7nfpCOsL._AC_UL320_.jpg",
  "https://m.media-amazon.com/images/I/61boPLs0aAL._AC_UY218_.jpg",
  "https://m.media-amazon.com/images/I/911vH59-S+S._MCnd_AC_UL320_.jpg",
  "https://m.media-amazon.com/images/I/61IgehdgusL._AC_UL320_.jpg",
  "https://m.media-amazon.com/images/I/51P0D-ZgyVL._AC_UY218_.jpg",
  "https://m.media-amazon.com/images/I/81RSefBpCBL._AC_UL320_.jpg",
  "https://m.media-amazon.com/images/I/81qe4VEfaFS._AC_UL320_.jpg",
  "https://m.media-amazon.com/images/I/81VAhCfSAnL._AC_UY218_.jpg",
  "https://m.media-amazon.com/images/I/51tDwmmaSKL._AC_UY218_.jpg",
  "https://m.media-amazon.com/images/I/81I23VLUuzL._AC_UL320_.jpg",
];
